# Generated by Django 2.2.13 on 2021-10-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrg', models.DateField(blank=True, null=True)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, editable=False, null=True)),
                ('includePosts', models.BooleanField(default=True)),
                ('includeEvents', models.BooleanField(default=True)),
                ('includeOrganisations', models.BooleanField(default=True)),
                ('includeProjects', models.BooleanField(default=True)),
                ('includeResources', models.BooleanField(default=True)),
                ('includeTrainings', models.BooleanField(default=True)),
                ('nPosts', models.IntegerField(blank=True, editable=False, null=True)),
                ('nEvents', models.IntegerField(blank=True, editable=False, null=True)),
                ('nOrganisations', models.IntegerField(blank=True, editable=False, null=True)),
                ('nProjects', models.IntegerField(blank=True, editable=False, null=True)),
                ('nResources', models.IntegerField(blank=True, editable=False, null=True)),
                ('nTrainings', models.IntegerField(blank=True, editable=False, null=True)),
                ('sent', models.BooleanField(default=False, editable=False, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
