# Generated by Django 2.2.13 on 2021-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_auto_20210801_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
