# Generated by Django 2.2.13 on 2021-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_auto_20210801_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
