# Generated by Django 2.2.13 on 2021-08-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0005_digest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='hasOrganisations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='nOrganisations',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='hasProjects',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='hasResources',
            field=models.BooleanField(default=True),
        ),
    ]
