# Generated by Django 2.2.13 on 2021-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0006_auto_20210802_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='hasPosts',
            field=models.BooleanField(default=True),
        ),
    ]
