# Generated by Django 2.2.13 on 2021-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0007_digest_hasposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='hasEvents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='hasTrainings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='nEvents',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='nNews',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='nTrainings',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
