# Generated by Django 2.2.13 on 2021-08-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0008_auto_20210802_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digest',
            name='tobeSend',
        ),
    ]
