# Generated by Django 2.2.13 on 2021-08-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0009_remove_digest_tobesend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digest',
            old_name='nNews',
            new_name='nPosts',
        ),
    ]
