# Generated by Django 2.2.13 on 2021-08-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0010_auto_20210802_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digest',
            old_name='hasEvents',
            new_name='includeEvents',
        ),
        migrations.RenameField(
            model_name='digest',
            old_name='hasOrganisations',
            new_name='includeOrganisations',
        ),
        migrations.RenameField(
            model_name='digest',
            old_name='hasPosts',
            new_name='includePosts',
        ),
        migrations.RenameField(
            model_name='digest',
            old_name='hasProjects',
            new_name='includeProjects',
        ),
        migrations.RenameField(
            model_name='digest',
            old_name='hasResources',
            new_name='includeResources',
        ),
        migrations.RenameField(
            model_name='digest',
            old_name='hasTrainings',
            new_name='includeTrainings',
        ),
    ]
