# Generated by Django 2.2.13 on 2021-10-04 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0004_auto_20210808_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('dateUpdated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=3000)),
                ('contactPoint', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPointEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('projectlocality', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, max_length=300, null=True, upload_to='images/')),
                ('logoCredit', models.CharField(blank=True, max_length=300, null=True)),
                ('profileImage', models.ImageField(blank=True, max_length=300, null=True, upload_to='images/')),
                ('profileImageCredit', models.CharField(blank=True, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_creator', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ManyToManyField(to='organisations.Organisation')),
            ],
        ),
    ]
