# Generated by Django 2.2.13 on 2021-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20211008_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforms',
            name='croppingLogo',
        ),
        migrations.RemoveField(
            model_name='platforms',
            name='croppingProfileImage',
        ),
        migrations.AlterField(
            model_name='platforms',
            name='logo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='profileImage',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
