# Generated by Django 3.2.23 on 2023-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20230502_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='description_de',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_el',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_en',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_es',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_et',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_fr',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_hu',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_it',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_lt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_nl',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_pt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description_sv',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
