# Generated by Django 3.2.23 on 2023-11-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20231109_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
