# Generated by Django 2.2.13 on 2021-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20211011_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='geographicExtend',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'Global'), ('MACRO-REGIONAL', 'Macro-regional'), ('NATIONAL', 'National'), ('SUB-NATIONAL', 'Sub-national'), ('REGIONAL', 'Regional'), ('CITY', 'City'), ('NEIGHBOURHOOD', 'Neighbourhood')], max_length=15, null=True),
        ),
    ]
