# Generated by Django 2.2.13 on 2021-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_platform_geographicextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='geographicExtend',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('MACRO-REGIONAL', 'Macro-regional'), ('NATIONAL', 'National'), ('SUB-NATIONAL', 'Sub-national'), ('REGIONAL', 'Regional'), ('CITY', 'City'), ('NEIGHBOURHOOD', 'Neighbourhood')], max_length=15),
        ),
    ]
