# Generated by Django 3.2.23 on 2023-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0004_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link1', models.CharField(max_length=200)),
                ('link2', models.CharField(max_length=200)),
                ('link3', models.CharField(max_length=200)),
                ('link4', models.CharField(max_length=200)),
                ('link5', models.CharField(max_length=200)),
                ('link6', models.CharField(max_length=200)),
                ('link7', models.CharField(max_length=200)),
                ('link8', models.CharField(max_length=200)),
                ('slug1', models.CharField(max_length=200)),
                ('slug2', models.CharField(max_length=200)),
                ('slug3', models.CharField(max_length=200)),
                ('slug4', models.CharField(max_length=200)),
                ('slug5', models.CharField(max_length=200)),
                ('slug6', models.CharField(max_length=200)),
                ('slug7', models.CharField(max_length=200)),
                ('slug8', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
