# Generated by Django 3.2.23 on 2023-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0006_auto_20231107_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_name1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
