# Generated by Django 3.2.23 on 2023-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0008_auto_20231107_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_el', models.CharField(max_length=200, null=True)),
                ('title_hu', models.CharField(max_length=200, null=True)),
                ('title_it', models.CharField(max_length=200, null=True)),
                ('title_lt', models.CharField(max_length=200, null=True)),
                ('title_pt', models.CharField(max_length=200, null=True)),
                ('title_sv', models.CharField(max_length=200, null=True)),
                ('title_et', models.CharField(max_length=200, null=True)),
                ('title_nl', models.CharField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_es', models.TextField(null=True)),
                ('content_fr', models.TextField(null=True)),
                ('content_de', models.TextField(null=True)),
                ('content_el', models.TextField(null=True)),
                ('content_hu', models.TextField(null=True)),
                ('content_it', models.TextField(null=True)),
                ('content_lt', models.TextField(null=True)),
                ('content_pt', models.TextField(null=True)),
                ('content_sv', models.TextField(null=True)),
                ('content_et', models.TextField(null=True)),
                ('content_nl', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='images/')),
            ],
        ),
    ]
