# Generated by Django 3.2.23 on 2023-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0012_homesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
