# Generated by Django 3.2.23 on 2023-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0014_auto_20231109_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='position',
            field=models.CharField(choices=[('float-left', 'left'), ('float-right', 'right')], max_length=15),
        ),
    ]
