# Generated by Django 3.2.23 on 2023-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0017_auto_20231111_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, max_length=300, null=True, upload_to='images/')),
                ('platform_name', models.CharField(max_length=200)),
                ('platform_description', models.TextField()),
                ('platform_url', models.URLField()),
            ],
        ),
    ]
