# Generated by Django 3.2.23 on 2023-11-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0018_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='platform_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_sv',
            field=models.TextField(null=True),
        ),
    ]
