# Generated by Django 2.2.13 on 2021-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsa', '0005_auto_20210521_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
