# Generated by Django 2.2.10 on 2020-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200329_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sticky',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
    ]
