# Generated by Django 2.2.10 on 2020-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sticky',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
