# Generated by Django 3.2.23 on 2023-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
