# Generated by Django 3.2.23 on 2023-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20231105_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
