# Generated by Django 3.2.23 on 2023-11-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20231105_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Pages'},
        ),
    ]
