# Generated by Django 3.2.23 on 2024-03-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_pages_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_el',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_et',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_hu',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_lt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_nl',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_el',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_et',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_lt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_sv',
        ),
    ]
