# Generated by Django 2.2.8 on 2020-01-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('dateUpdated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('origin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('aim', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('topic', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('imageCredit', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('host', models.CharField(max_length=100)),
                ('howToParticipate', models.CharField(max_length=300)),
                ('equipment', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
