# Generated by Django 2.2.9 on 2020-01-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
