# Generated by Django 2.2.13 on 2021-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedproject',
            name='needsUpdate',
            field=models.BooleanField(default=False),
        ),
    ]
