# Generated by Django 2.2.13 on 2021-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fundingBody',
        ),
        migrations.AddField(
            model_name='project',
            name='fundingBody',
            field=models.ManyToManyField(blank=True, to='projects.FundingBody'),
        ),
    ]
