# Generated by Django 2.2.13 on 2021-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_translatedproject_needsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
