# Generated by Django 2.2.9 on 2020-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200124_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
