# Generated by Django 2.2.13 on 2021-09-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatedDescription', models.CharField(max_length=3000)),
                ('inLanguage', models.TextField(max_length=2)),
            ],
        ),
    ]
