# Generated by Django 2.2.13 on 2021-10-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211025_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participationtask',
            old_name='participationtask',
            new_name='participationTask',
        ),
    ]
