# Generated by Django 2.2.13 on 2021-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_translateddescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatedDescription', models.CharField(max_length=3000)),
                ('translatedAim', models.CharField(max_length=2000)),
                ('translatedHotToParticipate', models.CharField(max_length=2000)),
                ('translatedequipment', models.CharField(max_length=2000)),
                ('inLanguage', models.TextField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='translatedDescriptions',
        ),
        migrations.DeleteModel(
            name='TranslatedDescription',
        ),
        migrations.AddField(
            model_name='project',
            name='translatedProject',
            field=models.ManyToManyField(to='projects.TranslatedProject'),
        ),
    ]
