# Generated by Django 2.2.10 on 2020-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200204_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keywords',
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='projects.Keyword'),
        ),
    ]
