# Generated by Django 2.2.13 on 2021-09-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20210926_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatedproject',
            old_name='translatedHotToParticipate',
            new_name='translatedHowToParticipate',
        ),
        migrations.AddField(
            model_name='translatedproject',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
