# Generated by Django 2.2.10 on 2020-02-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200218_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=300, upload_to='images/'),
        ),
    ]
