# Generated by Django 2.2.10 on 2020-02-24 11:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200220_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default='ES', max_length=2),
            preserve_default=False,
        ),
    ]
