# Generated by Django 2.2.10 on 2020-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nvoters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
