# Generated by Django 2.2.10 on 2020-03-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_followedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(default='Author', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='author_email',
            field=models.CharField(default='author@email.com', max_length=100),
            preserve_default=False,
        ),
    ]
