# Generated by Django 2.2.10 on 2020-03-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200302_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aim',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
