# Generated by Django 2.2.10 on 2020-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200304_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='howToParticipate',
            field=models.CharField(max_length=1000),
        ),
    ]
