# Generated by Django 2.2.10 on 2020-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200304_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aim',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
