# Generated by Django 2.2.10 on 2020-03-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200310_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imageCredit',
            new_name='imageCredit1',
        ),
    ]
