# Generated by Django 2.2.10 on 2020-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20200310_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hidden',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
