# Generated by Django 2.2.10 on 2020-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20200310_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='customField',
            field=models.ManyToManyField(to='projects.CustomField'),
        ),
    ]
