# Generated by Django 2.2.10 on 2020-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_hidden'),
        ('projects', '0025_auto_20200312_1154'),
    ]

    operations = [
    ]
