# Generated by Django 2.2.10 on 2020-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projectpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aim',
            field=models.CharField(max_length=2000),
        ),
    ]
