# Generated by Django 2.2.10 on 2020-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200324_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageCredit1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageCredit2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageCredit3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
