# Generated by Django 2.2.10 on 2020-03-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20200327_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
