# Generated by Django 2.2.10 on 2020-04-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200328_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fundingAgency',
        ),
        migrations.DeleteModel(
            name='FundingAgency',
        ),
    ]
