# Generated by Django 2.2.10 on 2020-04-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20200401_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
