# Generated by Django 2.2.10 on 2020-05-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20200518_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedProjects',
            new_name='ApprovedProjects',
        ),
    ]
