# Generated by Django 2.2.10 on 2020-05-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20200519_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='top',
            new_name='featured',
        ),
    ]
