# Generated by Django 2.2.10 on 2020-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20200519_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundingProgram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageCredit2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='originUID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='originURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
