# Generated by Django 2.2.10 on 2020-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20200603_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
