# Generated by Django 2.2.10 on 2020-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20200603_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customField',
            field=models.ManyToManyField(blank=True, to='projects.CustomField'),
        ),
    ]
