# Generated by Django 2.2.13 on 2020-08-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20200624_1222'),
        ('projects', '0040_project_organisation'),
    ]

    operations = [
    ]
