# Generated by Django 2.2.13 on 2020-08-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200814_1238'),
        ('projects', '0045_merge_20200814_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mainOrganisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_organisation', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
