# Generated by Django 2.2.13 on 2020-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20200821_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
