# Generated by Django 2.2.13 on 2020-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20200831_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participationtask', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='participationtask',
            field=models.ManyToManyField(to='projects.ParticipationTask'),
        ),
    ]
