# Generated by Django 2.2.13 on 2020-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20200907_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographicextend', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='geographicextend',
            field=models.ManyToManyField(to='projects.GeographicExtend'),
        ),
    ]
