# Generated by Django 2.2.13 on 2020-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20200907_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectlocality',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
