# Generated by Django 2.2.10 on 2021-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_project_description_citizen_science_aspects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participatingInaContest',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
