# Generated by Django 2.2.13 on 2021-10-26 00:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0054_project_participatinginacontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultyLevel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasTag', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='participationtask',
            old_name='participationtask',
            new_name='participationTask',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='participationtask',
            new_name='participationTask',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='projectGeographicLocation',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='fundingBody',
        ),
        migrations.AddField(
            model_name='project',
            name='fundingBody',
            field=models.ManyToManyField(blank=True, to='projects.FundingBody'),
        ),
        migrations.AlterField(
            model_name='project',
            name='geographicextend',
            field=models.ManyToManyField(blank=True, to='projects.GeographicExtend'),
        ),
        migrations.CreateModel(
            name='TranslatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatedDescription', models.CharField(max_length=3000)),
                ('translatedAim', models.CharField(max_length=2000)),
                ('translatedHowToParticipate', models.CharField(max_length=2000)),
                ('translatedEquipment', models.CharField(max_length=2000)),
                ('inLanguage', models.TextField(max_length=5)),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('needsUpdate', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='difficultyLevel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.DifficultyLevel'),
        ),
        migrations.AddField(
            model_name='project',
            name='hasTag',
            field=models.ManyToManyField(to='projects.HasTag'),
        ),
        migrations.AddField(
            model_name='project',
            name='translatedProject',
            field=models.ManyToManyField(to='projects.TranslatedProject'),
        ),
    ]
