# Generated by Django 2.2.13 on 2021-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_project_participatinginacontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasTag', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='hasTag',
            field=models.ManyToManyField(to='projects.HasTag'),
        ),
    ]
