# Generated by Django 2.2.13 on 2021-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20210617_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultyLevel', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='difficultyLevel',
            field=models.ManyToManyField(to='projects.DifficultyLevel'),
        ),
    ]
