# Generated by Django 2.2.13 on 2021-06-18 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20210618_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='difficultyLevel',
        ),
        migrations.AddField(
            model_name='project',
            name='difficultyLevel',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='projects.DifficultyLevel'),
            preserve_default=False,
        ),
    ]
