# Generated by Django 2.2 on 2021-11-16 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0056_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(related_name='project_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
