# Generated by Django 2.2.13 on 2021-06-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20210618_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficultyLevel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.DifficultyLevel'),
        ),
    ]
