# Generated by Django 2.2.13 on 2022-09-12 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20211118_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateUpdated',
            field=models.DateTimeField(verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='doingAtHome',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='project_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='hasTag',
            field=models.ManyToManyField(blank=True, to='projects.HasTag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='projects.Keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participatingInaContest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='participationTask',
            field=models.ManyToManyField(blank=True, to='projects.ParticipationTask'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ManyToManyField(blank=True, to='projects.Topic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='translatedProject',
            field=models.ManyToManyField(blank=True, to='projects.TranslatedProject'),
        ),
    ]
