# Generated by Django 2.2.13 on 2022-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20220912_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateUpdated',
            field=models.DateTimeField(null=True, verbose_name='Updated date'),
        ),
    ]
