# Generated by Django 2.2.13 on 2021-06-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20210618_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficultyLevel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.DifficultyLevel'),
        ),
    ]
