# Generated by Django 2.2.13 on 2021-06-20 17:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20210618_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectGeographicLocation',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
