# Generated by Django 2.2.28 on 2023-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20221020_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='stats',
            field=models.ManyToManyField(blank=True, to='projects.Stats'),
        ),
    ]
