# Generated by Django 2.2.13 on 2021-06-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_project_projectgeographiclocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
    ]
