# Generated by Django 2.2.28 on 2023-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20230401_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
