# Generated by Django 2.2.28 on 2023-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20230402_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
