# Generated by Django 2.2.28 on 2023-04-07 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0068_auto_20230407_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Follows',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='bookmarks',
            new_name='follows',
        ),
        migrations.AddField(
            model_name='project',
            name='totalFollowers',
            field=models.IntegerField(default=0),
        ),
    ]
