# Generated by Django 2.2.28 on 2023-04-08 09:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20230407_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('day', models.DateField(auto_now_add=True, null=True)),
                ('count', models.IntegerField(default=1)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Topic')),
            ],
        ),
    ]
