# Generated by Django 2.2.28 on 2023-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_searchstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstats',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
