# Generated by Django 2.2.28 on 2023-04-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_searchstats_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchstats',
            old_name='registered',
            new_name='user_registered',
        ),
    ]
