# Generated by Django 2.2.10 on 2023-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20230408_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstats',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
