# Generated by Django 2.2.28 on 2023-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20230408_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstats',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchstats',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
