# Generated by Django 2.2.10 on 2023-04-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20230408_1210'),
        ('projects', '0074_remove_searchstats_count'),
    ]

    operations = [
    ]
