# Generated by Django 2.2.28 on 2023-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_remove_searchstats_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstats',
            name='http_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
