# Generated by Django 2.2.28 on 2023-04-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_searchstats_http_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchstats',
            old_name='http_host',
            new_name='remote_host',
        ),
    ]
