# Generated by Django 2.2.28 on 2023-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20230408_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchstats',
            old_name='remote_host',
            new_name='user_agent',
        ),
    ]
