# Generated by Django 2.2.10 on 2023-04-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_merge_20230408_1349'),
        ('projects', '0077_auto_20230408_1407'),
    ]

    operations = [
    ]
