# Generated by Django 2.2.13 on 2023-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20230410_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstats',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
