# Generated by Django 3.2.23 on 2023-11-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20231108_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_sv',
            field=models.TextField(null=True),
        ),
    ]
