# Generated by Django 3.2.23 on 2023-11-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20231108_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aim_de',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_el',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_es',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_et',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_fr',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_hu',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_it',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_lt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_nl',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_pt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aim_sv',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_el',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_et',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_hu',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_it',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_lt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_nl',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_sv',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_de',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_el',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_es',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_et',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_fr',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_hu',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_it',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_lt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_nl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_sv',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_de',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_el',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_es',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_et',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_fr',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_hu',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_it',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_lt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_nl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='howToParticipate_sv',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
