# Generated by Django 3.2.23 on 2023-11-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20231108_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aim',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_el',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_et',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_hu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_it',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_lt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_nl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_pt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_sv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_citizen_science_aspects',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='howToParticipate_sv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
