# Generated by Django 3.2.23 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptext',
            name='paragraph_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
