# Generated by Django 3.2.23 on 2023-11-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20231120_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_citizen_science_aspects',
            new_name='citizen_science_aspects_description',
        ),
    ]
