# Generated by Django 3.2.23 on 2024-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_auto_20240327_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
