# Generated by Django 2.2.13 on 2021-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecsa_fee',
        ),
    ]
