# Generated by Django 2.2.10 on 2020-05-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
