# Generated by Django 2.2.13 on 2020-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200515_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
