# Generated by Django 2.2.13 on 2023-07-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20230410_1005'),
        ('organisations', '0008_organisation_logocredit'),
        ('events', '0009_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='mainOrganisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_coordinated', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_associated', to='projects.Project'),
        ),
    ]
