# Generated by Django 2.2.13 on 2023-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20230724_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
