# Generated by Django 2.2.13 on 2023-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='online_event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'On-line event'), ('facetoface', 'Face-to-face event')], default='online', max_length=20),
        ),
    ]
