# Generated by Django 2.2.13 on 2023-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20230726_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'On-line event'), ('face-to-face', 'Face-to-face event')], default='online', max_length=20),
        ),
    ]
