# Generated by Django 3.2.23 on 2023-11-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20231109_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sv',
            field=models.TextField(null=True),
        ),
    ]
