# Generated by Django 3.2.23 on 2024-09-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20240412_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'On-line event'), ('face-to-face', 'Face-to-face event'), ('hybrid', 'Hybrid event')], default='online', max_length=20),
        ),
    ]
