# Generated by Django 2.2.13 on 2021-06-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestArea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('bio', models.CharField(blank=True, max_length=400, null=True, verbose_name='Short Bio and disciplinary background')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('orcid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID (If you have registered on the ORCID platform for researchers and have a persistent digital identifier (your ORCID iD) you can add it here to link this profile with your professional information such as affiliations, grants, publications, peer review, and more.)')),
                ('interestAreas', models.ManyToManyField(blank=True, to='profiles.InterestArea')),
                ('organisation', models.ManyToManyField(blank=True, to='organisations.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
