# Generated by Django 2.2.13 on 2021-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID (If you have registered on the ORCID platform for researchers and have a persistentdigital identifier (your ORCID iD) you can add it here to link this profile with your professionalinformation such as affiliations, grants, publications, peer review, and more.)'),
        ),
    ]
