# Generated by Django 2.2.10 on 2020-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200225_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interestAreas',
            field=models.ManyToManyField(blank=True, to='profiles.InterestArea'),
        ),
    ]
