# Generated by Django 2.2.13 on 2021-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210806_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='profile',
            name='digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visibleProfile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Short Bio and disciplinary background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID (If you have registered on the ORCID platform for researchers and havea persistent digital identifier (your ORCID iD) you can add it here to link thisprofile with your professional information such as affiliations, grants, publications,peer review, and more.)'),
        ),
    ]
