# Generated by Django 2.2.10 on 2020-05-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200225_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID'),
        ),
    ]
