# Generated by Django 2.2.13 on 2021-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visibleProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='Your profile is visible (email is not showed)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='digest',
            field=models.BooleanField(default=True, verbose_name='Allow us to send monthly digests describing new content in the platform'),
        ),
    ]
