# Generated by Django 2.2.13 on 2020-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institution',
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID (If you have registered on the ORCID platform for researchers and have a persistent digital identifier (your ORCID iD) you can add it here to link this profile with your professional information such as affiliations, grants, publications, peer review, and more.)'),
        ),
    ]
