# Generated by Django 2.2.13 on 2021-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210807_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submittedisVisible',
            field=models.BooleanField(default=True, verbose_name='Others can see the list of content you uploaded'),
        ),
    ]
