# Generated by Django 2.2.13 on 2021-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201104_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ManyToManyField(blank=True, null=True, to='organisations.Organisation'),
        ),
    ]
