# Generated by Django 2.2 on 2021-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20211026_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileVisible',
            field=models.BooleanField(default=False),
        ),
    ]
