# Generated by Django 2.2.13 on 2021-11-25 07:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20211116_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manageProjectesFromCountry',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
