# Generated by Django 2.2.13 on 2021-04-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210409_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ecsa_invoice_id',
            new_name='ecsa_member_number',
        ),
    ]
