# Generated by Django 2.2.13 on 2021-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210412_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ecsa_old_member_fee',
            field=models.BooleanField(default=False, verbose_name='Old member fee'),
        ),
    ]
