# Generated by Django 3.2.4 on 2024-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20211125_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ecsaMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ecsaMemberDelegate',
            field=models.BooleanField(default=False),
        ),
    ]
