# Generated by Django 2.2.13 on 2021-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_ecsa_old_member_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ecsa_old_member_fee',
            field=models.BooleanField(default=False, verbose_name='Reduced fee for CSA/ACSA members'),
        ),
    ]
