# Generated by Django 3.2.4 on 2024-08-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20240802_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ecsaMember',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ecsaMemberDelegate',
        ),
    ]
