# Generated by Django 2.2.13 on 2021-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210506_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ecsa_old_member_fee',
            field=models.BooleanField(default=False, verbose_name='20% discount for CSA/ACSA members'),
        ),
    ]
