# Generated by Django 2.2.13 on 2021-05-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_ecsa_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecsa_fee',
        ),
    ]
