# Generated by Django 2.2.13 on 2021-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_delete_ecsa_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ecsa_billing_email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Bio and disciplinary background'),
        ),
    ]
