# Generated by Django 2.2.13 on 2021-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_profile_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
