# Generated by Django 2.2.13 on 2021-06-02 06:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_profile_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='ecsa_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='postal_code',
            new_name='ecsa_postal_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='ecsa_street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='ecsa_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
