# Generated by Django 2.2.13 on 2021-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20210602_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ecsa_member',
            new_name='paid',
        ),
    ]
