# Generated by Django 2.2.13 on 2021-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20210608_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ecsa_community_mailing_list',
            field=models.BooleanField(default=False, verbose_name='I want to be added to the members-only ECSA community mailing list, which provides early notices of jobs, funding opportunities, project requests, and webinars with a limited number of registrations, etc. and where I can exchange with other members.'),
        ),
    ]
