# Generated by Django 2.2.13 on 2021-07-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_profile_ecsa_community_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ecsa_community_mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
