# Generated by Django 2.2.8 on 2020-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='document',
            name='about',
            field=models.CharField(default='sts', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='aggregateRating',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='audience',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.CharField(default='img', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='inLanguage',
            field=models.CharField(default='en', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(default='key', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='license',
            field=models.CharField(default='license', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='publisher',
            field=models.CharField(default='publisher', max_length=100),
            preserve_default=False,
        ),
    ]
