# Generated by Django 2.2.13 on 2021-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dateUpdated',
        ),
        migrations.AddField(
            model_name='resource',
            name='dateUpdated2',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
