# Generated by Django 2.2.13 on 2021-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
