# Generated by Django 2.2.9 on 2020-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourcegroup_resourcesgrouped'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcesgrouped',
            unique_together={('group', 'resource')},
        ),
    ]
