# Generated by Django 2.2.13 on 2021-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_bookmarkedresources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='educationLevel',
        ),
        migrations.AddField(
            model_name='resource',
            name='educationLevel',
            field=models.ManyToManyField(to='resources.EducationLevel'),
        ),
    ]
