# Generated by Django 2.2.10 on 2020-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resourcegroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='keywords',
        ),
        migrations.AddField(
            model_name='resource',
            name='keywords',
            field=models.ManyToManyField(to='resources.Keyword'),
        ),
    ]
