# Generated by Django 2.2.10 on 2020-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_savedresources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='author',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='resource',
            name='author_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='author_rsc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
