# Generated by Django 2.2.10 on 2020-03-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20200302_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='datePublished',
        ),
        migrations.AddField(
            model_name='resource',
            name='dateUploaded',
            field=models.DateTimeField(default='2000-12-12', verbose_name='Date Uploaded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='imageURL',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='resourceDOI',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Audience'),
        ),
        migrations.AddField(
            model_name='resource',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resources.Theme'),
            preserve_default=False,
        ),
    ]
