# Generated by Django 2.2.10 on 2020-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_auto_20200304_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='author_rsc',
            new_name='authors',
        ),
    ]
