# Generated by Django 2.2.10 on 2020-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20200304_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='imageURL',
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(max_length=300, upload_to='images/'),
        ),
    ]
