# Generated by Django 2.2.10 on 2020-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_resource_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='audience',
        ),
        migrations.AddField(
            model_name='resource',
            name='audience',
            field=models.ManyToManyField(blank=True, null=True, to='resources.Audience'),
        ),
    ]
