# Generated by Django 2.2.10 on 2020-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20200317_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=models.ManyToManyField(to='resources.Audience'),
        ),
    ]
