# Generated by Django 2.2.10 on 2020-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_resourcepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image2',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
