# Generated by Django 2.2.10 on 2020-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_resource_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='abstract',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceDOI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
