# Generated by Django 2.2.10 on 2020-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_auto_20200324_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='datePublished',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
