# Generated by Django 2.2.10 on 2020-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_auto_20200324_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='abstract',
            field=models.CharField(max_length=3000),
        ),
    ]
