# Generated by Django 2.2.10 on 2020-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_auto_20200324_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='top',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
