# Generated by Django 2.2.10 on 2020-05-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_resource_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredresources',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
