# Generated by Django 2.2.10 on 2020-05-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_auto_20200518_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedResources',
            new_name='ApprovedResources',
        ),
    ]
