# Generated by Django 2.2.10 on 2020-05-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_auto_20200519_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='top',
            new_name='featured',
        ),
    ]
