# Generated by Django 2.2.13 on 2020-06-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20200519_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='aggregateRating',
        ),
    ]
