# Generated by Django 2.2.13 on 2020-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_remove_resource_aggregaterating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.AlterField(
            model_name='resource',
            name='image1',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
