# Generated by Django 2.2.13 on 2020-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0035_merge_20200814_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author_email',
        ),
        migrations.AddField(
            model_name='resource',
            name='imageCredit1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='imageCredit2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
