# Generated by Django 2.2.13 on 2020-08-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_auto_20200827_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationLevel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningResourceType', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='conditionsOfAccess',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='isTrainingResource',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='timeRequired',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='educationLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.EducationLevel'),
        ),
        migrations.AddField(
            model_name='resource',
            name='learningResourceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.LearningResourceType'),
        ),
    ]
