# Generated by Django 2.2.13 on 2020-09-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0037_auto_20200828_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dateLastModification',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last modification'),
        ),
    ]
