# Generated by Django 2.2.13 on 2020-09-11 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_resource_datelastmodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateLastModification',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modification'),
        ),
    ]
