# Generated by Django 2.2.13 on 2021-02-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0041_auto_20201104_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='own',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
