# Generated by Django 2.2.13 on 2021-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_resource_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects',
            field=models.CharField(default='Field added at the beginning of May for moderation purposes', max_length=2000),
            preserve_default=False,
        ),
    ]
