# Generated by Django 2.2.13 on 2021-10-26 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0055_auto_20211026_0019'),
        ('resources', '0043_resource_description_citizen_science_aspects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dateLastModification',
        ),
        migrations.AddField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AddField(
            model_name='resource',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='educationLevel',
        ),
        migrations.AddField(
            model_name='resource',
            name='educationLevel',
            field=models.ManyToManyField(to='resources.EducationLevel'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='learningResourceType',
        ),
        migrations.AddField(
            model_name='resource',
            name='learningResourceType',
            field=models.ManyToManyField(to='resources.LearningResourceType'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='BookmarkedResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
