# Generated by Django 3.2.23 on 2023-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_auto_20231109_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='abstract_de',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_el',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_en',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_es',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_et',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_fr',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_hu',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_it',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_lt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_nl',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_pt',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='abstract_sv',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_de',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_el',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_es',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_et',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_fr',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_hu',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_it',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_lt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_nl',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_pt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_citizen_science_aspects_sv',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
