# Generated by Django 3.2.23 on 2023-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0050_auto_20231109_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
