# Generated by Django 3.2.23 on 2023-11-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0051_auto_20231109_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_sv',
            field=models.TextField(null=True),
        ),
    ]
