# Generated by Django 3.2.23 on 2023-11-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0052_auto_20231109_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_sv',
            field=models.TextField(null=True),
        ),
    ]
