# Generated by Django 3.2.23 on 2023-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0054_auto_20231109_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningresourcetype',
            name='learningResourceType_sv',
            field=models.TextField(null=True),
        ),
    ]
