# Generated by Django 3.2.23 on 2024-09-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0058_auto_20240412_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_el',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_et',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_lt',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_sv',
        ),
    ]
