# Generated by Django 3.2.23 on 2023-11-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'TopBar',
                'ordering': ['-position'],
            },
        ),
    ]
