# Generated by Django 3.2.23 on 2023-11-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0005_auto_20231107_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='link1',
            new_name='link_name1',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link2',
            new_name='link_name2',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link3',
            new_name='link_name3',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link4',
            new_name='link_name4',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link5',
            new_name='link_name5',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link6',
            new_name='link_name6',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link7',
            new_name='link_name7',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='link8',
            new_name='link_name8',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug1',
            new_name='link_url1',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug2',
            new_name='link_url2',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug3',
            new_name='link_url3',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug4',
            new_name='link_url4',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug5',
            new_name='link_url5',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug6',
            new_name='link_url6',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug7',
            new_name='link_url7',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='slug8',
            new_name='link_url8',
        ),
    ]
