# Generated by Django 3.2.23 on 2023-11-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0009_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomeSection',
        ),
        migrations.RenameField(
            model_name='homesection',
            old_name='sectionName',
            new_name='name',
        ),
    ]
