# Generated by Django 3.2.23 on 2023-11-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0010_auto_20231109_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSection',
        ),
    ]
