# Generated by Django 3.2.23 on 2023-11-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0015_alter_homesection_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='position',
            field=models.CharField(choices=[('float-start', 'left'), ('float-end', 'right')], max_length=15),
        ),
    ]
