# Generated by Django 3.2.23 on 2023-11-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0016_alter_homesection_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'verbose_name_plural': 'HomeSection'},
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='position',
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_position',
            field=models.CharField(choices=[('order-1', 'left'), ('order-2', 'right')], default='left', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homesection',
            name='image_position',
            field=models.CharField(choices=[('order-1', 'left'), ('order-2', 'right')], default='left', max_length=15),
            preserve_default=False,
        ),
    ]
