# Generated by Django 3.2.23 on 2024-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eucitizensciencetheme', '0020_auto_20240327_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name1_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name2_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name3_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name4_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name5_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name6_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name7_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_el',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_et',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_hu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_lt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_name8_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='platform_description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
