# Generated by Django 2.2.13 on 2020-07-30 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0032_auto_20200519_1015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0039_auto_20200519_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('dateUpdated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('logo', models.ImageField(max_length=300, upload_to='images/')),
                ('contactPoint', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPointEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=150)),
                ('associatedProjects', models.ManyToManyField(to='projects.Project')),
                ('associatedResources', models.ManyToManyField(to='resources.Resource')),
                ('communityMembers', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('orgType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationType')),
            ],
        ),
    ]
