# Generated by Django 2.2.13 on 2020-08-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='associatedProjects',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='associatedResources',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='communityMembers',
        ),
    ]
