# Generated by Django 2.2.13 on 2021-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.URLField(),
        ),
    ]
