# Generated by Django 2.2.13 on 2020-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200814_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.AddField(
            model_name='organisation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
