# Generated by Django 2.2.13 on 2020-08-31 10:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200831_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
