# Generated by Django 2.2.13 on 2021-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20210808_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contactPointEmail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
