# Generated by Django 2.2.13 on 2021-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20210416_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ecsa_member',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ecsa_member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ecsa_payment_revision',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ecsa_requested_join',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
