# Generated by Django 2.2.13 on 2022-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20211026_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logoCredit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
