# Generated by Django 2.2.13 on 2021-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisation_legal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='has_vat_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_status',
            field=models.IntegerField(choices=[(0, 'Profit'), (1, 'Non-profit')]),
        ),
    ]
