# Generated by Django 3.2.23 on 2023-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20231109_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_sv',
            field=models.TextField(null=True),
        ),
    ]
