# Generated by Django 3.2.23 on 2023-11-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_auto_20231109_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
