# Generated by Django 2.2.13 on 2021-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_auto_20210427_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='has_vat_number',
        ),
    ]
