# Generated by Django 2.2.13 on 2021-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_remove_organisation_has_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='origin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_status',
            field=models.IntegerField(choices=[(0, 'For-profit'), (1, 'Non-profit')]),
        ),
    ]
