# Generated by Django 2.2.13 on 2021-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_auto_20210506_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ecsa_member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
