# Generated by Django 2.2.13 on 2021-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_organisation_ecsa_member_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='legal_status',
            field=models.IntegerField(blank=True, choices=[(0, 'For-profit'), (1, 'Non-profit')], null=True),
        ),
    ]
