# Generated by Django 3.2.23 on 2024-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_auto_20240327_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptext',
            name='paragraph_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='paragraph_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='helptext',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='type_sv',
            field=models.TextField(null=True),
        ),
    ]
