# Generated by Django 3.2.4 on 2024-08-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_auto_20240412_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ecsaMember',
            field=models.BooleanField(default=False),
        ),
    ]
