# Generated by Django 2.2.13 on 2021-05-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_auto_20210521_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='delegate1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate1', to='ecsa.Delegate'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='delegate2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate2', to='ecsa.Delegate'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='mainDelegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_delegate', to='ecsa.Delegate'),
        ),
    ]
