# Generated by Django 2.2.13 on 2021-06-02 06:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_auto_20210521_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ecsa_billing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
