# Generated by Django 2.2.13 on 2021-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_auto_20210602_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
