# Generated by Django 2.2.13 on 2021-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_auto_20210608_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ecsa_old_organisation_fee',
            field=models.BooleanField(default=False, verbose_name='20% discount for CSA/ACSA members'),
        ),
    ]
