# Generated by Django 2.2.13 on 2021-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0019_auto_20210608_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='ecsa_member',
            new_name='paid',
        ),
    ]
